# Name of workflow
name: Cypress and Test Workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - main
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm install

      # Start the server in the background
      - name: Start server
        run: npm run start &
        env:
          NODE_ENV: test  # Asegúrate de que el servidor se inicie en modo de prueba si es necesario

      # Wait for the server to be ready
      - name: Wait for server
        run: npx wait-on http://localhost:3001  # Asegúrate de que la URL coincida con tu servidor

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run

      # Run build
      - name: Run Build
        run: npm run build

      # Run tests
      - name: Run Tests
        run: npm run test