# Name of workflow
name: Test workflow doesnt work

# Trigger workflow on all push events to the main branch
on:
  push:
    branches: [main]

# Jobs to carry out
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: 🧰 Install Deps
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Start Server and Run Cypress Tests
        run: npx start-server-and-test "npm run start" http://localhost:3001 "npm run cypress:run"
        env:
          CI: true
          MONGODB_URI: mongodb://localhost:27017/techquiz