# Name of workflow
name: Test PR

# Trigger workflow on all push events to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

# Jobs to carry out
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start server and run Cypress E2E tests
        run: |
          # Ensure the server binds to 0.0.0.0 for external access
          export HOST=0.0.0.0
          export PORT=3001
          npx start-server-and-test "npm run start:server" http://localhost:3001 "npx cypress run --e2e"
        env:
          CI: true
          MONGODB_URI: mongodb+srv://sieke13:gerardo123@sieke13.3gkpd.mongodb.net/
