# Name of workflow
name: CI

# Trigger workflow on push and pull requests
on: [push, pull_request]

# Jobs to carry out
jobs:
  build-and-test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    
    services:
      # Add MongoDB service
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the app
      - name: Build the app
        run: npm run build

      # Start the server in the background
      - name: Start server
        run: npm run start:ci &
        env:
          NODE_ENV: test  # Asegúrate de que el servidor se inicie en modo de prueba si es necesario

      # Wait for the server to be ready
      - name: Wait for server
        run: npx wait-on http://localhost:3001  # Espera a que el servidor esté listo

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run